// ──────────────────────────────────────────────────
// Problem  : 3568. Minimum Moves to Clean the Classroom
// Difficulty: Medium
// Tags     : Array, Hash Table, Bit Manipulation, Breadth-First Search, Matrix
// Link     : https://leetcode.com/problems/minimum-moves-to-clean-the-classroom/
// Runtime  : 135 ms (beats 90%)
// Memory   : 61696000 (beats 69%)
// Language : java
// Copyright: (c) 2026 srinivaseswar. All rights reserved.
// Synced by: leetie
// ──────────────────────────────────────────────────

import java.util.*;

class Solution {
    public int minMoves(String[] classroom, int energy) {
            int m = classroom.length;
                    int n = classroom[0].length();
                            int startR = -1, startC = -1;
                                    
                                            List<int[]> litterList = new ArrayList<>();
                                                    
                                                            for (int i = 0; i < m; i++) {
                                                                        for (int j = 0; j < n; j++) {
                                                                                        char ch = classroom[i].charAt(j);
                                                                                                        if (ch == 'S') {
                                                                                                                            startR = i;
                                                                                                                                                startC = j;
                                                                                                                                                                } else if (ch == 'L') {
                                                                                                                                                                                    litterList.add(new int[]{i, j});
                                                                                                                                                                                                    }
                                                                                                                                                                                                                }
                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                
                                                                                                                                                                                                                                        int k = litterList.size();
                                                                                                                                                                                                                                                if (k == 0) return 0; // No litter to collect
                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                int fullMask = (1 << k) - 1;
                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                // Map litter positions to bit index
                                                                                                                                                                                                                                                                                        int[][] litterIdx = new int[m][n];
                                                                                                                                                                                                                                                                                                for (int i = 0; i < m; i++) Arrays.fill(litterIdx[i], -1);
                                                                                                                                                                                                                                                                                                        for (int i = 0; i < k; i++) {
                                                                                                                                                                                                                                                                                                                    int[] pos = litterList.get(i);
                                                                                                                                                                                                                                                                                                                                litterIdx[pos[0]][pos[1]] = i;
                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                        // bestEnergy[r][c][mask] stores max energy remaining
                                                                                                                                                                                                                                                                                                                                                                int[][][] bestEnergy = new int[m][n][1 << k];
                                                                                                                                                                                                                                                                                                                                                                        for (int i = 0; i < m; i++) {
                                                                                                                                                                                                                                                                                                                                                                                    for (int j = 0; j < n; j++) {
                                                                                                                                                                                                                                                                                                                                                                                                    Arrays.fill(bestEnergy[i][j], -1);
                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                        // Queue state: {r, c, mask, curEnergy, steps}
                                                                                                                                                                                                                                                                                                                                                                                                                                                Queue<int[]> queue = new LinkedList<>();
                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Check if start position is on a litter or reset cell
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        int initialMask = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (litterIdx[startR][startC] != -1) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            initialMask |= (1 << litterIdx[startR][startC]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    queue.offer(new int[]{startR, startC, initialMask, energy, 0});
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            bestEnergy[startR][startC][initialMask] = energy;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            int[][] dirs = {{-1, 0}, {1, 0}, {0, -1}, {0, 1}};
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            while (!queue.isEmpty()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        int[] curr = queue.poll();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    int r = curr[0], c = curr[1], mask = curr[2], e = curr[3], steps = curr[4];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (mask == fullMask) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return steps;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // If out of energy, can't move further
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (e == 0) continue;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for (int[] d : dirs) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    int nr = r + d[0];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    int nc = c + d[1];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (nr >= 0 && nr < m && nc >= 0 && nc < n && classroom[nr].charAt(nc) != 'X') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        int nextEnergy = e - 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            char cell = classroom[nr].charAt(nc);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Reset energy at 'R'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (cell == 'R') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                nextEnergy = energy;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            int nextMask = mask;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (litterIdx[nr][nc] != -1) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        nextMask |= (1 << litterIdx[nr][nc]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Only visit if we reach this state with strictly greater energy
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (nextEnergy > bestEnergy[nr][nc][nextMask]) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                bestEnergy[nr][nc][nextMask] = nextEnergy;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        queue.offer(new int[]{nr, nc, nextMask, nextEnergy, steps + 1});
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return -1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }